//! Simple File System (SFS) implementation for creo.
//!
//! This module provides a basic Unix-like file system with the following features:
//! - Superblock-based metadata tracking
//! - Inode-based file representation with direct and indirect pointers
//! - Directory hierarchy with root directory at inode 0
//! - Bitmap-based allocation tracking for inodes and data blocks
//! - Support for file creation, deletion, reading, and writing
//! - Path-based file lookup with directory traversal
//!
//! # Disk Layout
//! ```text
//! Block 0: Superblock
//! Block 1: Inode Bitmap
//! Block 2: Data Block Bitmap
//! Block 3+: Inode Table (10% of disk capacity)
//! Remaining: Data Blocks (90% of disk capacity)
//! ```
//!
//! TODO: Documentation generated by copilot -- verify them!
//! TODO: Need to refactor this, file too big and contains stale unused methods

use super::{block_dev::BlockDevice, layout::*};
use crate::fs::layout::FileType::File;
use crate::println;
use crate::virtio::OsHal;
use alloc::string::ToString;
use alloc::{string::String, vec::Vec};
use core::convert::TryFrom;
use core::ptr::write;
use pc_keyboard::KeyCode::P;
use virtio_drivers::device::blk::VirtIOBlk;
use virtio_drivers::transport::pci::PciTransport;
use zerocopy::{FromBytes, IntoBytes, KnownLayout, U16, U32, U64};

/// Magic number used to identify a valid SFS filesystem.
/// Stored in the superblock for filesystem validation during mount.
const MAGIC_NUMBER: u32 = 0x_DEAD_BEEF;

/// Inode number for the root directory of the filesystem.
/// The root directory is always at inode 0 by convention.
const ROOT_DIRECTORY_INODE: u64 = 0;

// TODO: Write a Wrapper for the VirtIoBlkDevice --- currently just using the trait implementations

/// SFS - Simple File System
///
/// The main filesystem structure that manages all filesystem operations.
/// Generic over any type implementing the `BlockDevice` trait, allowing flexibility
/// in the underlying storage mechanism (e.g., VirtIO block device, RAM disk, etc.).
#[derive(Debug)]
#[repr(C)]
pub struct SFS<D: BlockDevice> {
	/// The underlying block device used for persistent storage.
	device: D,
	/// Cached copy of the superblock containing filesystem metadata.
	/// This avoids repeated disk reads for frequently accessed metadata.
	superblock: SuperBlock,
}

impl<D: BlockDevice> SFS<D> {
	/// writes the superblock in the block device at block_id: 0
	///
	/// Formats a block device with a new SFS filesystem.
	///
	/// This operation:
	/// 1. Validates the device has sufficient capacity (minimum 100 blocks)
	/// 2. Allocates 10% of disk space for the inode table
	/// 3. Allocates 90% of disk space for data blocks
	/// 4. Initializes the superblock with filesystem metadata
	/// 5. Writes empty bitmaps for inode and data block tracking
	///
	/// # Arguments
	/// * `device` - The block device to format
	///
	/// # Returns
	/// * `Ok(Self)` - A new SFS instance with the formatted device
	/// * `Err(FileSystemError::FormatFailed)` - If device capacity is too small
	/// * `Err(FileSystemError::BlockError)` - If any block write operation fails
	///
	/// # Warning
	/// This operation will destroy all existing data on the device!
	pub fn format(mut device: D) -> Result<Self, FileSystemError> {
		println!("[FS] Formatting Device");

		let capacity: u64 = device.capacity() as u64;
		if capacity < 100 {
			return Err(FileSystemError::FormatFailed);
		}
		let inode_table_blocks = capacity / 10; // 10% of the total capacity goes to the INODE_TABLE
		let inode_count = inode_table_blocks * INODES_PER_BLOCK as u64;

		let data_block_start = INODE_TABLE_START_BLOCK + inode_table_blocks;
		let data_block_count = capacity - data_block_start; // this works … think about it

		let sb = SuperBlock {
			magic_number: MAGIC_NUMBER,
			total_blocks: capacity,
			inode_bitmap_block: INODE_BITMAP_BLOCK,
			data_bitmap_block: DATA_BITMAP_BLOCK,
			inode_table_start_block: INODE_TABLE_START_BLOCK,
			inode_count,
			data_block_start,
			data_block_count,
		};

		let mut superblock_buffer = [0u8; BLOCK_SIZE];
		let dsb = DiskSuperBlock::from(sb);

		superblock_buffer[..size_of::<DiskSuperBlock>()].copy_from_slice(dsb.as_bytes());

		device
			.write_blocks(SUPERBLOCK_BLOCK, &superblock_buffer)
			.map_err(|_| FileSystemError::BlockError)?;

		let empty_bitmap_block = [0u8; BLOCK_SIZE];
		// Writing the INODE BITMAP BLOCK
		device
			.write_blocks(INODE_BITMAP_BLOCK, empty_bitmap_block.as_bytes())
			.map_err(|_| FileSystemError::BlockError)?;
		// Writing the DATA BITMAP BLOCK
		device
			.write_blocks(DATA_BITMAP_BLOCK, empty_bitmap_block.as_bytes())
			.map_err(|_| FileSystemError::BlockError)?;

		Ok(Self { device, superblock: sb })
	}

	/// Mounts an existing file system from a block device
	///
	/// Loads and validates an existing SFS filesystem from a block device.
	///
	/// This operation:
	/// 1. Reads the superblock from block 0
	/// 2. Validates the magic number (0xDEADBEEF)
	/// 3. Performs sanity checks on filesystem layout parameters
	/// 4. Returns a mounted SFS instance ready for operations
	///
	/// # Arguments
	/// * `device` - The block device containing an SFS filesystem
	///
	/// # Returns
	/// * `Ok(Self)` - A mounted SFS instance
	/// * `Err(FileSystemError::InvalidSuperBlock)` - If superblock validation fails
	/// * `Err(FileSystemError::BlockError)` - If block read operation fails
	///
	/// # Sanity Checks
	/// - Magic number must match MAGIC_NUMBER
	/// - Inode count must be evenly divisible by INODES_PER_BLOCK
	/// - Bitmap blocks must be at expected locations
	/// - Data block range must not exceed total blocks
	pub fn mount(mut device: D) -> Result<Self, FileSystemError> {
		println!("[FS] Mounting File System");
		let mut buffer = [0u8; BLOCK_SIZE];

		device
			.read_blocks(SUPERBLOCK_BLOCK, &mut buffer)
			.map_err(|_| FileSystemError::InvalidSuperBlock)?;

		println!("[FS] Read into buffer {:?}", buffer);

		let size = size_of::<DiskSuperBlock>();
		let disk_superblock = DiskSuperBlock::ref_from_bytes(&buffer[..size])
			.map_err(|_| FileSystemError::InvalidSuperBlock)?;

		let superblock = SuperBlock::try_from(*disk_superblock)
			.map_err(|_| FileSystemError::InvalidSuperBlock)?;

		if superblock.magic_number != MAGIC_NUMBER {
			println!("[FS] Superblock magic number match failed");
			return Err(FileSystemError::InvalidSuperBlock);
		}

		// basic sanity checks so that we stay in range
		if superblock.inode_count % (INODES_PER_BLOCK as u64) != 0 {
			return Err(FileSystemError::InvalidSuperBlock);
		}
		if superblock.inode_table_start_block != INODE_TABLE_START_BLOCK {
			return Err(FileSystemError::InvalidSuperBlock);
		}
		if superblock.inode_bitmap_block != INODE_BITMAP_BLOCK
			|| superblock.data_bitmap_block != DATA_BITMAP_BLOCK
		{
			return Err(FileSystemError::InvalidSuperBlock);
		}
		if superblock.data_block_start <= superblock.inode_table_start_block {
			return Err(FileSystemError::InvalidSuperBlock);
		}
		if superblock.data_block_start + superblock.data_block_count > superblock.total_blocks {
			return Err(FileSystemError::InvalidSuperBlock);
		}

		Ok(Self { device, superblock })
	}

	/// Allocates a new inode from the filesystem.
	///
	/// Finds the first free inode by scanning the inode bitmap, marks it as allocated,
	/// and returns its index. Uses a read-modify-write pattern to ensure consistency.
	///
	/// # Returns
	/// * `Ok(u64)` - The index of the newly allocated inode
	/// * `Err(FileSystemError::NoSpace)` - If no free inodes are available
	/// * `Err(FileSystemError::BlockError)` - If bitmap read/write fails
	///
	/// # Process
	/// 1. Read the inode bitmap block from disk
	/// 2. Find and set the first free bit
	/// 3. Write the updated bitmap back to disk
	/// 4. Return the inode index
	pub fn allocate_inode(&mut self) -> Result<u64, FileSystemError> {
		let mut bitmap_buffer = [0u8; BLOCK_SIZE];

		self.device
			.read_blocks(INODE_BITMAP_BLOCK, &mut bitmap_buffer)
			.map_err(|_| FileSystemError::BlockError)?;

		// we gotta wrap the buffer around this to work on it as a Bitmap
		let mut inode_bitmap = Bitmap::new(&mut bitmap_buffer);

		let free_inode_index =
			inode_bitmap.find_and_set_first_free().ok_or(FileSystemError::NoSpace)?;

		// here we're working a reference of the bitmap_buffer -- so it is still valid and can be
		// passed as the buffer to the write_blocks

		if free_inode_index >= self.superblock.inode_count as usize {
			// out of bounds index is allocated .. not gonna work
			return Err(FileSystemError::NoSpace);
		}
		// so the write_blocks of the BlockDevice should be able to overwrite the contents of the
		// block if any exists
		self.device
			.write_blocks(self.superblock.inode_bitmap_block, &bitmap_buffer)
			.map_err(|_| FileSystemError::BlockError)?;

		Ok(free_inode_index as u64)
	}

	/// Allocates a data block following a read-modify-write pattern
	///
	/// Finds the first free data block by scanning the data bitmap, marks it as allocated,
	/// zeros the block content to avoid stale data, and returns its absolute block number.
	///
	/// # Returns
	/// * `Ok(u64)` - The absolute block number of the newly allocated data block
	/// * `Err(FileSystemError::NoSpace)` - If no free data blocks are available
	/// * `Err(FileSystemError::BlockError)` - If bitmap or block read/write fails
	///
	/// # Process
	/// 1. Read the data bitmap block from disk
	/// 2. Find and set the first free bit
	/// 3. Calculate the absolute block number
	/// 4. Zero out the new block to avoid stale data
	/// 5. Write the updated bitmap back to disk
	pub fn allocate_data_block(&mut self) -> Result<u64, FileSystemError> {
		// TODO: maybe wrap the u64 here with something similar to FileHandler .. better to have
		let mut bm_buffer = [0u8; BLOCK_SIZE];

		self.device
			.read_blocks(DATA_BITMAP_BLOCK, &mut bm_buffer)
			.map_err(|_| FileSystemError::BlockError)?;

		let mut data_bitmap = Bitmap::new(&mut bm_buffer);

		let free_idx = data_bitmap.find_and_set_first_free().ok_or(FileSystemError::NoSpace)?;

		if free_idx >= self.superblock.data_block_count as usize {
			return Err(FileSystemError::NoSpace);
		}

		self.device
			.write_blocks(DATA_BITMAP_BLOCK, &bm_buffer)
			.map_err(|_| FileSystemError::BlockError)?;

		// find position in the table
		let abs_block = self.superblock.data_block_start + free_idx as u64;

		// zeroing the new block to avoid stale data
		let zero_block = [0u8; BLOCK_SIZE];
		self.device
			.write_blocks(abs_block, &zero_block)
			.map_err(|_| FileSystemError::BlockError)?;

		Ok(abs_block)
	}

	/// Reads an inode from disk by its index.
	///
	/// Locates the inode in the inode table and deserializes it from disk format
	/// to the in-memory representation.
	///
	/// # Arguments
	/// * `inode_index` - The inode number to read
	///
	/// # Returns
	/// * `Ok(Inode)` - The deserialized inode
	/// * `Err(FileSystemError::BlockError)` - If block read or deserialization fails
	///
	/// # Implementation Details
	/// - Calculates which block contains the inode (4 inodes per 512-byte block)
	/// - Calculates the offset within that block
	/// - Reads the block and extracts the DiskInode
	/// - Converts DiskInode to Inode (little-endian to native byte order)
	pub fn read_inode(
		&mut self,
		inode_index: u64,
	) -> Result<Inode, FileSystemError> {
		let block_num =
			self.superblock.inode_table_start_block + (inode_index / INODES_PER_BLOCK as u64);

		let offset_in_block = (inode_index % INODES_PER_BLOCK as u64) as usize * INODE_SIZE;

		let mut buffer = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(block_num, &mut buffer)
			.map_err(|_| FileSystemError::BlockError)?;

		// so here we read the disk inode from the buffer
		let size = size_of::<DiskInode>();
		let disk_inode =
			DiskInode::ref_from_bytes(&buffer[offset_in_block..(offset_in_block + size)])
				.map_err(|_| FileSystemError::BlockError)?;

		let inode = Inode::try_from(*disk_inode).map_err(|_| FileSystemError::BlockError)?;

		Ok(inode)
	}

	/// Writes an inode to disk at a specific index.
	///
	/// Updates an existing inode or writes a newly created inode to its location
	/// in the inode table. Uses a read-modify-write pattern to preserve other
	/// inodes in the same block.
	///
	/// # Arguments
	/// * `inode` - The inode data to write
	/// * `inode_idx` - The inode number where to write
	///
	/// # Returns
	/// * `Ok(())` - If the inode was successfully written
	/// * `Err(FileSystemError::BlockError)` - If block read/write fails
	///
	/// # Implementation Details
	/// - Calculates the block containing the inode
	/// - Reads the entire block to preserve other inodes
	/// - Converts Inode to DiskInode (native to little-endian byte order)
	/// - Writes the DiskInode bytes at the correct offset
	/// - Writes the modified block back to disk
	pub fn write_inode(
		&mut self,
		inode: Inode,
		inode_idx: u64,
	) -> Result<(), FileSystemError> {
		// then we have to know which actual inode to write this into
		// the free_inode_idx is just the index of the bit in the inode_bitmap
		// so we gotta fetch the inode tables now, then index from those tables

		let block_num =
			self.superblock.inode_table_start_block + (inode_idx / INODES_PER_BLOCK as u64);

		let offset_in_block = (inode_idx % INODES_PER_BLOCK as u64) as usize * INODE_SIZE;

		let mut buffer = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(block_num, &mut buffer)
			.map_err(|_| FileSystemError::BlockError)?;

		// so here we read the disk inode from the buffer
		let disk_inode = DiskInode::from(inode);
		//let inode_m = Inode::try_from(disk_inode).unwrap();
		let size = size_of::<DiskInode>();
		let inode_slice = &mut buffer[offset_in_block..(offset_in_block + size)];
		inode_slice.copy_from_slice(disk_inode.as_bytes());

		self.device
			.write_blocks(block_num, &buffer)
			.map_err(|_| FileSystemError::BlockError)?;

		Ok(())
	}

	/// Adds a new directory entry into a directory block buffer at a given slot index
	///
	/// A block would have multiple directory entries, slot is the index of this.
	///
	/// Writes a directory entry (mapping filename to inode) into a specific slot
	/// within a directory block buffer. Does not write to disk - the caller must
	/// write the modified block.
	///
	/// # Arguments
	/// * `block` - The directory block buffer to modify (must be BLOCK_SIZE)
	/// * `slot` - The directory entry slot index (0-7 for a 512-byte block)
	/// * `inode` - The inode number this directory entry points to
	/// * `name` - The filename as a byte slice
	///
	/// # Returns
	/// * `Ok(())` - If the entry was successfully written to the buffer
	/// * `Err(FileSystemError::NameTooLong)` - If name exceeds DIR_NAME_MAX (52 bytes)
	///
	/// # Implementation Details
	/// - Creates a DiskDirEntry with the DIRENT_USED flag set
	/// - Copies the name bytes into the fixed-size name field
	/// - Serializes the entry into the appropriate slot in the block buffer
	pub fn write_dirent_into_block(
		&self,
		block: &mut [u8; BLOCK_SIZE],
		slot: usize,
		inode: u64,
		name: &[u8],
	) -> Result<(), FileSystemError> {
		if name.len() > DIR_NAME_MAX {
			return Err(FileSystemError::NameTooLong);
		}

		let start = slot * DIR_ENTRY_SIZE;
		let end = start + DIR_ENTRY_SIZE;

		// Build an entry
		let mut entry_bytes = [0u8; DIR_ENTRY_SIZE];
		// Safe because DiskDirEntry is IntoBytes and exactly DIR_ENTRY_SIZE
		let mut entry = DiskDirEntry {
			inode: U64::new(inode),
			name_len: U16::new(name.len() as u16),
			flags: U16::new(DIRENT_USED),
			name: [0u8; DIR_NAME_MAX],
		};

		entry.name[..name.len()].copy_from_slice(name);
		// make the above entry into a buffer
		entry_bytes.copy_from_slice(entry.as_bytes());

		block[start..end].copy_from_slice(&entry_bytes);
		Ok(())
	}

	/// Find free slot in a directory block (first block only for now), returns slot index
	///
	/// Scans a directory block to find the first unused slot for a new directory entry.
	/// A slot is considered free if either the DIRENT_USED flag is not set or the
	/// inode number is 0.
	///
	/// # Arguments
	/// * `block` - The directory block buffer to scan
	///
	/// # Returns
	/// * `Some(usize)` - The index of the first free slot (0-7 for 512-byte blocks)
	/// * `None` - If all slots in the block are occupied
	///
	/// # Implementation Details
	/// - Iterates through all DIR_ENTRIES_PER_BLOCK slots (8 per block)
	/// - Checks both the DIRENT_USED flag and inode number
	/// - Returns the first slot where either condition indicates it's free
	pub fn find_free_dir_slot(
		&self,
		block: &[u8; BLOCK_SIZE],
	) -> Option<usize> {
		for i in 0..DIR_ENTRIES_PER_BLOCK {
			let start = i * DIR_ENTRY_SIZE;
			let end = start + DIR_ENTRY_SIZE;

			if let Ok(entry) = DiskDirEntry::ref_from_bytes(&block[start..end]) {
				let used = (entry.flags.get() & DIRENT_USED) != 0;
				let inode = entry.inode.get();

				if !used || inode == 0 {
					return Some(i);
				}
			}
		}
		None
	}

	// Initialize Root Directory: Inode 0, allocate one data block
	/// Initializes the root directory at inode 0 with one empty data block.
	///
	/// This function must be called after formatting a new filesystem to set up
	/// the root directory structure. It ensures inode 0 is marked as allocated
	/// and creates an empty directory inode pointing to a single data block.
	///
	/// # Returns
	/// * `Ok(())` - If root directory was successfully initialized
	/// * `Err(FileSystemError::BlockError)` - If any block operation fails
	/// * `Err(FileSystemError::NoSpace)` - If no data blocks are available
	///
	/// # Implementation Details
	/// - Marks inode 0 as allocated in the inode bitmap
	/// - Allocates one data block for directory entries
	/// - Creates an inode with FileType::Directory
	/// - Sets the first direct pointer to the allocated block
	/// - Writes the inode to disk at index 0
	pub fn init_root_directory(&mut self) -> Result<(), FileSystemError> {
		let mut ibuf = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(INODE_BITMAP_BLOCK, &mut ibuf)
			.map_err(|_| FileSystemError::BlockError)?;

		{
			let mut bm = Bitmap::new(&mut ibuf);
			if !bm.is_set(0) {
				bm.set(0);
			}
		}

		self.device
			.write_blocks(INODE_BITMAP_BLOCK, &ibuf)
			.map_err(|_| FileSystemError::BlockError)?;

		let data_block = self.allocate_data_block()?;

		let mut root = Inode {
			mode: FileType::Directory,
			user_id: 0,
			group_id: 0,
			link_count: 2, // "." and ".."
			size_in_bytes: 0,
			last_access_time: 0,
			last_modification_time: 0,
			creation_time: 0,
			direct_pointers: [0u64; 10],
			indirect_pointer: 0,
		};

		root.direct_pointers[0] = data_block;
		self.write_inode(root, 0)?;

		let mut dir_block = [0u8; BLOCK_SIZE];
		self.write_dirent_into_block(&mut dir_block, 0, 0, b".")?;
		self.write_dirent_into_block(&mut dir_block, 1, 0, b"..")?;

		self.device
			.write_blocks(data_block, &dir_block)
			.map_err(|_| FileSystemError::BlockError)?;

		Ok(())
	}

	/// Adds a directory entry to the root directory.
	///
	/// Creates a mapping from a filename to an inode number in the root directory's
	/// first data block. This is used when creating new files or subdirectories.
	///
	/// # Arguments
	/// * `inode` - The inode number to associate with this filename
	/// * `name` - The filename (must not exceed DIR_NAME_MAX bytes)
	///
	/// # Returns
	/// * `Ok(())` - If the entry was successfully added
	/// * `Err(FileSystemError::NameTooLong)` - If filename exceeds DIR_NAME_MAX
	/// * `Err(FileSystemError::CorruptLayout)` - If root directory has no data block
	/// * `Err(FileSystemError::NoSpace)` - If directory block has no free slots
	/// * `Err(FileSystemError::BlockError)` - If block read/write fails
	///
	/// # Implementation Details
	/// - Reads the root inode (inode 0)
	/// - Locates the first data block of the root directory
	/// - Finds a free slot in the directory block
	/// - Writes the new directory entry to that slot
	/// - Writes the modified block back to disk
	pub fn add_root_dir_entry(
		&mut self,
		inode: u64,
		name: &str,
	) -> Result<(), FileSystemError> {
		if name.as_bytes().len() > DIR_NAME_MAX {
			return Err(FileSystemError::NameTooLong);
		}

		// Root is inode 0
		let root = self.read_inode(0)?;
		let block = root.direct_pointers[0];

		if block == 0 {
			return Err(FileSystemError::CorruptLayout);
		}

		let mut dir_block = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(block, &mut dir_block)
			.map_err(|_| FileSystemError::BlockError)?;

		let slot = self.find_free_dir_slot(&dir_block).ok_or(FileSystemError::NoSpace)?;

		self.write_dirent_into_block(&mut dir_block, slot, inode, name.as_bytes())?;

		self.device
			.write_blocks(block, &dir_block)
			.map_err(|_| FileSystemError::BlockError)?;

		Ok(())
	}

	/// Creates a new file in the root directory (internal helper function).
	///
	/// This is a low-level function that handles the core logic of file creation:
	/// allocating an inode, checking for name conflicts, and updating the directory.
	///
	/// # Arguments
	/// * `name` - The filename (must not be empty or exceed DIR_NAME_MAX bytes)
	///
	/// # Returns
	/// * `Ok((inode_index, dir_block))` - Tuple of the new inode number and directory block
	/// * `Err(FileSystemError::NameTooLong)` - If filename is invalid
	/// * `Err(FileSystemError::CorruptLayout)` - If root directory structure is invalid
	/// * `Err(FileSystemError::AlreadyExists)` - If a file with the same name exists
	/// * `Err(FileSystemError::NoSpace)` - If no free slots or inodes are available
	/// * `Err(FileSystemError::BlockError)` - If block operations fail
	///
	/// # Implementation Details
	/// - Validates filename length and emptiness
	/// - Reads root directory and its first data block
	/// - Scans directory entries to check for name conflicts
	/// - Finds the first empty slot in the directory
	/// - Allocates a new inode with FileType::File
	/// - Writes the directory entry to the found slot
	/// - Persists the updated directory block to disk
	fn create_file_in_root(
		&mut self,
		name: &str,
	) -> Result<(u64 /*inode index*/, u64 /*dir block*/), FileSystemError> {
		if name.as_bytes().len() > DIR_NAME_MAX || name.is_empty() {
			return Err(FileSystemError::NameTooLong);
		}

		// Read root directory block
		let root_dir_inode = self.read_inode(ROOT_DIRECTORY_INODE)?;
		if root_dir_inode.mode != FileType::Directory {
			return Err(FileSystemError::CorruptLayout);
		}

		let dir_block = root_dir_inode.direct_pointers[0];
		if dir_block == 0 {
			return Err(FileSystemError::CorruptLayout);
		}
		let mut dir_block_buf = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(dir_block, &mut dir_block_buf)
			.map_err(|_| FileSystemError::BlockError)?;

		// Collision check and find slot
		let mut empty_slot_index: Option<usize> = None;
		let entries = DirEntryBlock::new(&dir_block_buf);
		for (i, entry) in entries.enumerate() {
			let is_used = (entry.flags.get() & DIRENT_USED) != 0;
			if is_used {
				let entry_name_len = entry.name_len.get() as usize;
				if &entry.name[..entry_name_len] == name.as_bytes() {
					println!("[FS] File with same name found");
					return Err(FileSystemError::AlreadyExists); // use FileError::FileExists at
					// call site
				}
			} else if empty_slot_index.is_none() {
				empty_slot_index = Some(i);
			}
		}

		let slot_index = empty_slot_index.ok_or(FileSystemError::NoSpace)?;

		// Allocate inode and write it
		let inode_index = self.allocate_inode()?;
		let new_inode = Inode {
			mode: FileType::File,
			user_id: 0,
			group_id: 0,
			link_count: 1,
			size_in_bytes: 0,
			last_access_time: 0,
			last_modification_time: 0,
			creation_time: 0,
			direct_pointers: [0u64; 10],
			indirect_pointer: 0,
		};
		self.write_inode(new_inode, inode_index)?;

		// Write directory entry into buffer
		self.write_dirent_into_block(&mut dir_block_buf, slot_index, inode_index, name.as_bytes())?;

		// PERSIST THE UPDATED DIRECTORY BLOCK (this was missing)
		self.device
			.write_blocks(dir_block, &dir_block_buf)
			.map_err(|_| FileSystemError::BlockError)?;

		Ok((inode_index, dir_block))
	}

	/// Creates a new file in a specified parent directory (internal helper function).
	///
	/// Similar to `create_file_in_root` but works with any directory inode as the parent.
	/// This enables creating files in subdirectories (when subdirectory support is added).
	///
	/// # Arguments
	/// * `parent_inode_num` - The inode number of the parent directory
	/// * `filename` - The name for the new file
	///
	/// # Returns
	/// * `Ok((new_inode_index, parent_dir_data_block))` - Tuple of new inode and parent's data block
	/// * `Err(FileSystemError::NameTooLong)` - If filename is invalid
	/// * `Err(FileSystemError::CorruptLayout)` - If parent is not a directory or has no data block
	/// * `Err(FileSystemError::AlreadyExists)` - If filename already exists in parent directory
	/// * `Err(FileSystemError::NoSpace)` - If no free slots or inodes available
	/// * `Err(FileSystemError::BlockError)` - If block operations fail
	///
	/// # Implementation Details
	/// - Verifies parent inode is a directory
	/// - Reads parent directory's first data block
	/// - Checks for filename collision
	/// - Allocates new inode with FileType::File
	/// - Updates parent directory with new entry
	/// - Persists changes to disk
	fn create_file_in_dir(
		&mut self,
		parent_inode_num: u64,
		filename: &str,
	) -> Result<(u64 /*new inode index*/, u64 /*parent dir data block*/), FileSystemError> {
		if filename.as_bytes().len() > DIR_NAME_MAX || filename.is_empty() {
			return Err(FileSystemError::NameTooLong);
		}

		let parent_dir_inode = self.read_inode(parent_inode_num)?;
		if parent_dir_inode.mode != FileType::Directory {
			// Can't create a file inside a file!
			return Err(FileSystemError::CorruptLayout);
		}

		// get the parent's data block
		// (assumes one block per dir for now)
		let parent_dir_data_block = parent_dir_inode.direct_pointers[0];
		if parent_dir_data_block == 0 {
			// This shouldn't happen for a correctly initialized directory
			return Err(FileSystemError::CorruptLayout);
		}

		let mut parent_dir_block_buf = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(parent_dir_data_block, &mut parent_dir_block_buf)
			.map_err(|_| FileSystemError::BlockError)?;

		// collision check
		let mut empty_slot_index: Option<usize> = None;
		let entries = DirEntryBlock::new(&parent_dir_block_buf);
		for (i, entry) in entries.enumerate() {
			let is_used = (entry.flags.get() & DIRENT_USED) != 0;
			if is_used {
				let entry_name_len = entry.name_len.get() as usize;
				if &entry.name[..entry_name_len] == filename.as_bytes() {
					println!("[FS] File with same name found");
					return Err(FileSystemError::AlreadyExists);
				}
			} else if empty_slot_index.is_none() {
				empty_slot_index = Some(i);
			}
		}

		let slot_index = empty_slot_index.ok_or(FileSystemError::NoSpace)?;

		let new_inode_index = self.allocate_inode()?;
		let new_inode = Inode {
			mode: FileType::File,
			user_id: 0,
			group_id: 0,
			link_count: 1,
			size_in_bytes: 0,
			last_access_time: 0,
			last_modification_time: 0,
			creation_time: 0,
			direct_pointers: [0u64; 10],
			indirect_pointer: 0,
		};
		self.write_inode(new_inode, new_inode_index)?;

		self.write_dirent_into_block(
			&mut parent_dir_block_buf,
			slot_index,
			new_inode_index,
			filename.as_bytes(),
		)?;

		self.device
			.write_blocks(parent_dir_data_block, &parent_dir_block_buf)
			.map_err(|_| FileSystemError::BlockError)?;

		Ok((new_inode_index, parent_dir_data_block))
	}

	/// Creates a new subdirectory in the root directory.
	///
	/// Allocates an inode and data block for the new directory, initializes it with
	/// "." (self-reference) and ".." (parent reference) entries, and adds it to the
	/// root directory listing.
	///
	/// # Arguments
	/// * `name` - The directory name (must not be empty or exceed DIR_NAME_MAX bytes)
	///
	/// # Returns
	/// * `Ok(u64)` - The inode number of the newly created directory
	/// * `Err(FileSystemError::NameTooLong)` - If name is invalid
	/// * `Err(FileSystemError::CorruptLayout)` - If root directory structure is invalid
	/// * `Err(FileSystemError::AlreadyExists)` - If directory name already exists
	/// * `Err(FileSystemError::NoSpace)` - If no free resources available
	/// * `Err(FileSystemError::BlockError)` - If block operations fail
	///
	/// # Implementation Details
	/// - Checks for name collision in root directory
	/// - Allocates inode with FileType::Directory and link_count=2
	/// - Allocates data block for directory entries
	/// - Writes "." entry pointing to itself
	/// - Writes ".." entry pointing to root (inode 0)
	/// - Updates root directory with new entry
	fn create_directory_in_root(
		&mut self,
		name: &str,
	) -> Result<u64, FileSystemError> {
		if name.as_bytes().len() > DIR_NAME_MAX || name.is_empty() {
			return Err(FileSystemError::NameTooLong);
			// should also include empty one but meh .. fix sometime later
		}

		let root_dir_inode = self.read_inode(ROOT_DIRECTORY_INODE)?;
		if root_dir_inode.mode != FileType::Directory {
			return Err(FileSystemError::CorruptLayout);
		}

		let dir_block_addr = root_dir_inode.direct_pointers[0];
		if dir_block_addr == 0 {
			return Err(FileSystemError::CorruptLayout);
		}

		let mut dir_block_buf = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(dir_block_addr, &mut dir_block_buf)
			.map_err(|_| FileSystemError::BlockError)?;

		// collision check
		let mut empty_slot_index: Option<usize> = None;
		let entries = DirEntryBlock::new(&dir_block_buf);
		for (i, entry) in entries.enumerate() {
			let is_used = (entry.flags.get() & DIRENT_USED) != 0;
			if is_used {
				let entry_name_len = entry.name_len.get() as usize;
				if &entry.name[..entry_name_len] == name.as_bytes() {
					println!("[FS] Directory with same name found");
					return Err(FileSystemError::AlreadyExists);
				}
			} else if empty_slot_index.is_none() {
				empty_slot_index = Some(i);
			}
		}
		let slot_index = empty_slot_index.ok_or(FileSystemError::NoSpace)?;

		// gotta allocate an inode and data block
		let new_inode_index = self.allocate_inode()?;
		let new_data_block = self.allocate_data_block()?;

		let mut new_inode = Inode {
			mode: FileType::Directory,
			user_id: 0,
			group_id: 0,
			link_count: 2,    // Starts with 2 (for . and parent's link to it)
			size_in_bytes: 0, // Dirs don't really use this
			last_access_time: 0,
			last_modification_time: 0,
			creation_time: 0,
			direct_pointers: [0u64; 10],
			indirect_pointer: 0,
		};

		// point new dir's inode to its new data block
		new_inode.direct_pointers[0] = new_data_block;
		self.write_inode(new_inode, new_inode_index)?;

		let mut new_dir_block = [0u8; BLOCK_SIZE];
		// "." points to itself
		self.write_dirent_into_block(&mut new_dir_block, 0, new_inode_index, b".")?;
		// ".." points to its parent (the root)
		self.write_dirent_into_block(&mut new_dir_block, 1, ROOT_DIRECTORY_INODE, b"..")?;

		self.device
			.write_blocks(new_data_block, &new_dir_block)
			.map_err(|_| FileSystemError::BlockError)?;

		self.write_dirent_into_block(
			&mut dir_block_buf,
			slot_index,
			new_inode_index,
			name.as_bytes(),
		)?;

		self.device
			.write_blocks(dir_block_addr, &dir_block_buf)
			.map_err(|_| FileSystemError::BlockError)?;

		println!("[FS] Created directory '{}' with inode #{}", name, new_inode_index);
		Ok(new_inode_index)
	}

	/// Searches for a directory entry by name within a directory's data block.
	///
	/// Scans all entries in the directory's first data block looking for a matching
	/// filename, and returns the inode number if found.
	///
	/// # Arguments
	/// * `dir_inode` - The inode of the directory to search in
	/// * `name` - The filename to search for
	///
	/// # Returns
	/// * `Ok(u64)` - The inode number associated with the filename
	/// * `Err(FileError::Corrupt)` - If the provided inode is not a directory
	/// * `Err(FileError::FileNotFound)` - If the directory has no data block or name not found
	/// * `Err(FileError::BlockReadError)` - If reading the directory block fails
	///
	/// # Implementation Details
	/// - Validates the inode is a directory type
	/// - Reads the first data block of the directory
	/// - Iterates through all directory entries
	/// - Compares entry names byte-by-byte with search name
	/// - Returns inode number on match, error if not found
	fn find_entry_in_dir(
		&mut self,
		dir_inode: &Inode,
		name: &str,
	) -> Result<u64, FileError> {
		if dir_inode.mode != FileType::Directory {
			return Err(FileError::Corrupt);
		}

		let data_block_addr = dir_inode.direct_pointers[0];
		if data_block_addr == 0 {
			return Err(FileError::FileNotFound);
		}

		let mut dir_block = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(data_block_addr, &mut dir_block)
			.map_err(|_| FileError::BlockReadError)?;

		let entries = DirEntryBlock::new(&dir_block);
		for e in entries {
			let used = (e.flags.get() & DIRENT_USED) != 0;
			if used {
				let nlen = e.name_len.get() as usize;
				if &e.name[..nlen] == name.as_bytes() {
					return Ok(e.inode.get());
				}
			}
		}
		// we went through the whole block but did not find it
		Err(FileError::FileNotFound)
	}

	/// Resolves a filesystem path to an inode number.
	///
	/// Parses a path string and traverses the directory hierarchy to find the
	/// corresponding inode. Supports absolute paths starting with "/" and handles
	/// directory traversal through multiple levels.
	///
	/// # Arguments
	/// * `path` - The path to resolve (e.g., "/", "/file.txt", "/dir/file.txt")
	///
	/// # Returns
	/// * `Ok(u64)` - The inode number of the file or directory at the path
	/// * `Err(FileError::FileNotFound)` - If any component of the path doesn't exist
	/// * `Err(FileError::Corrupt)` - If a non-directory is encountered in the path
	/// * `Err(FileError::BlockReadError)` - If reading directory blocks fails
	///
	/// # Implementation Details
	/// - Returns ROOT_DIRECTORY_INODE (0) for "/"
	/// - Splits path by "/" separator
	/// - Starts traversal from root directory
	/// - For each path component, looks it up in current directory
	/// - Reads the inode and continues if it's a directory
	/// - Returns the final inode number
	///
	/// # Examples
	/// - "/" -> inode 0 (root)
	/// - "/file.txt" -> inode of file in root
	/// - "/subdir/file.txt" -> inode of file in subdir
	fn find_inode_by_path(
		&mut self,
		path: &str,
	) -> Result<u64, FileError> {
		if path == "/" {
			return Ok(ROOT_DIRECTORY_INODE);
		}

		let mut current_inode_num = ROOT_DIRECTORY_INODE;
		let components = path.split('/').filter(|&s| !s.is_empty());

		for comp in components {
			let current_dir_inode =
				self.read_inode(current_inode_num).map_err(|_| FileError::Corrupt)?;

			let next_inode_num = self.find_entry_in_dir(&current_dir_inode, comp)?;
			current_inode_num = next_inode_num;
		}

		Ok(current_inode_num)
	}

	/// Splits a full path into its parent directory and its final component (basename).
	///
	/// Returns `(parent_path, basename)`.
	///
	/// Helper function for path manipulation, useful when creating or deleting files
	/// where you need to separate the parent directory from the target filename.
	///
	/// # Arguments
	/// * `path` - The full path to parse
	///
	/// # Returns
	/// A tuple of `(parent_path, basename)` where:
	/// - `parent_path` is the directory containing the file
	/// - `basename` is the final component (filename or directory name)
	///
	/// ### Examples
	/// * `/foo/bar.txt` -> `("/foo", "bar.txt")`
	/// * `/foo.txt`     -> `("/", "foo.txt")`
	/// * `foo.txt`      -> `(".", "foo.txt")` (Assumes relative to current dir)
	/// * `/`            -> `("/", "")`
	fn parse_path(path: &str) -> (&str, &str) {
		if path == "/" {
			return ("/", "");
		}

		match path.rsplit_once('/') {
			Some((parent, basename)) => {
				if parent.is_empty() {
					("/", basename)
				} else {
					(parent, basename)
				}
			},
			None => (".", path),
		}
	}

	// free helpers
	/// Frees an inode by clearing its allocation bit and zeroing its data.
	///
	/// Marks an inode as available for reuse by clearing its bit in the inode bitmap
	/// and zeroing out its data in the inode table. This is called when deleting files.
	///
	/// # Arguments
	/// * `inode_index` - The inode number to free
	///
	/// # Returns
	/// * `Ok(())` - If the inode was successfully freed
	/// * `Err(FileSystemError::BlockError)` - If bitmap or inode table operations fail
	///
	/// # Implementation Details
	/// - Reads the inode bitmap block
	/// - Clears the bit corresponding to the inode index
	/// - Writes the updated bitmap back to disk
	/// - Calculates which inode table block contains the inode
	/// - Zeroes out the inode's bytes in that block
	/// - Writes the updated inode table block back to disk
	fn free_inode(
		&mut self,
		inode_index: u64,
	) -> Result<(), FileSystemError> {
		let mut buffer = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(INODE_BITMAP_BLOCK, &mut buffer)
			.map_err(|_| FileSystemError::BlockError)?;
		{
			// clear the bit in inode bitmap block using bitmap
			let mut bm = Bitmap::new(&mut buffer);
			bm.clear(inode_index as usize);
		}

		self.device
			.write_blocks(INODE_BITMAP_BLOCK, &mut buffer)
			.map_err(|_| FileSystemError::BlockError)?;

		// now that we have removed the inode bitmap in its table
		// we need to remove the inode now
		// this is the entire block
		let in_block =
			self.superblock.inode_table_start_block + (inode_index / INODES_PER_BLOCK as u64);
		// this is location of the specific inode entry we have to clear
		let offset = (inode_index % INODES_PER_BLOCK as u64) as usize * INODE_SIZE;

		let mut in_buf = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(in_block, &mut in_buf)
			.map_err(|_| FileSystemError::BlockError)?;
		for b in &mut in_buf[offset..offset + INODE_SIZE] {
			*b = 0; // zero out the bits in this specific inode
		}
		self.device
			.write_blocks(in_block, &in_buf)
			.map_err(|_| FileSystemError::BlockError)?;

		Ok(())
	}

	/// Frees a data block by clearing its allocation bit in the data bitmap.
	///
	/// Marks a data block as available for reuse. Unlike `free_inode`, this does not
	/// zero the block content (that happens during allocation for security).
	///
	/// # Arguments
	/// * `abs_block` - The absolute block number to free
	///
	/// # Returns
	/// * `Ok(())` - If the block was successfully freed
	/// * `Err(FileSystemError::BlockError)` - If bitmap operations fail
	///
	/// # Implementation Details
	/// - Returns early if the block is not in the data region
	/// - Converts absolute block number to relative index in data region
	/// - Reads the data bitmap block
	/// - Clears the bit corresponding to the relative block index
	/// - Writes the updated bitmap back to disk
	///
	/// # Note
	/// The block content is not zeroed here; it will be zeroed when allocated again.
	fn free_data_block(
		&mut self,
		abs_block: u64,
	) -> Result<(), FileSystemError> {
		// abs block is the absolute block index
		if abs_block < self.superblock.data_block_start {
			return Ok(());
		}
		// get the relative data block from the data block start
		let rel = abs_block - self.superblock.data_block_start;
		let mut buf = [0u8; BLOCK_SIZE]; // to read the block into
		self.device
			.read_blocks(DATA_BITMAP_BLOCK, &mut buf)
			.map_err(|_| FileSystemError::BlockError)?;
		{
			let mut bmp = Bitmap::new(&mut buf);
			bmp.clear(rel as usize);
		}
		self.device
			.write_blocks(DATA_BITMAP_BLOCK, &buf)
			.map_err(|_| FileSystemError::BlockError)?;

		Ok(())
	}

	/// Finds a directory entry in the root directory by name.
	///
	/// Searches for a file or directory in the root directory and returns its slot
	/// index, inode number, the directory block buffer, and the block address.
	/// Useful for operations that need to modify directory entries (like deletion).
	///
	/// # Arguments
	/// * `name` - The filename to search for
	///
	/// # Returns
	/// * `Ok((slot_index, inode, dir_block_buffer, dir_block_addr))` - If found:
	///   - `slot_index`: The entry's slot in the directory block (0-7)
	///   - `inode`: The inode number of the file
	///   - `dir_block_buffer`: The entire directory block (for modification)
	///   - `dir_block_addr`: The absolute block address of the directory
	/// * `Err(FileSystemError::CorruptLayout)` - If root directory has no data block
	/// * `Err(FileSystemError::FileNotFound)` - If the name is not found
	/// * `Err(FileSystemError::BlockError)` - If block read fails
	///
	/// # Implementation Details
	/// - Reads root inode and its first data block
	/// - Iterates through directory entries
	/// - Compares entry names with search name
	/// - Returns slot info and buffers on match
	fn find_root_entry(
		&mut self,
		name: &str,
	) -> Result<(usize, u64 /*inode*/, [u8; BLOCK_SIZE], u64 /*dir block*/), FileSystemError> {
		let root_inode = self.read_inode(0)?;
		let blk = root_inode.direct_pointers[0];
		if blk == 0 {
			return Err(FileSystemError::CorruptLayout);
		}

		let mut dir_block = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(blk, &mut dir_block)
			.map_err(|_| FileSystemError::BlockError)?;

		let entries = DirEntryBlock::new(&dir_block);
		for (i, e) in entries.enumerate() {
			let used = (e.flags.get() & DIRENT_USED) != 0;
			if used {
				let nlen = e.name_len.get() as usize;
				if &e.name[..nlen] == name.as_bytes() {
					return Ok((i, e.inode.get(), dir_block, blk));
				}
			}
		}

		Err(FileSystemError::CorruptLayout)
	}

	/// Finds a directory entry in any directory with detailed information.
	///
	/// Similar to `find_root_entry` but works with any directory inode.
	/// Returns all the information needed to modify or delete the entry.
	///
	/// # Arguments
	/// * `parent_inode_num` - The inode number of the directory to search in
	/// * `filename` - The filename to search for
	///
	/// # Returns
	/// * `Ok((slot_index, file_inode, dir_block_buffer, dir_block_addr))` - If found:
	///   - `slot_index`: The entry's slot in the directory block (0-7)
	///   - `file_inode`: The inode number of the found file
	///   - `dir_block_buffer`: The entire directory block (for modification)
	///   - `dir_block_addr`: The absolute block address of the directory
	/// * `Err(FileError::Corrupt)` - If parent is not a directory or has no data block
	/// * `Err(FileError::FileNotFound)` - If filename not found in directory
	/// * `Err(FileError::BlockReadError)` - If block read fails
	///
	/// # Implementation Details
	/// - Reads the parent directory inode
	/// - Validates it's a directory type
	/// - Reads the directory's first data block
	/// - Scans entries for matching filename
	/// - Returns complete entry information
	fn find_entry_detailed(
		&mut self,
		parent_inode_num: u64,
		filename: &str,
	) -> Result<
		(
			usize,            /* slot index */
			u64,              /* file inode num */
			[u8; BLOCK_SIZE], /* parent dir block buffer */
			u64,              /* parent dir block address */
		),
		FileError,
	> {
		let parent_inode = self.read_inode(parent_inode_num).map_err(|_| FileError::Corrupt)?;
		if parent_inode.mode != FileType::Directory {
			return Err(FileError::Corrupt);
		}

		let dir_block_addr = parent_inode.direct_pointers[0];
		if dir_block_addr == 0 {
			return Err(FileError::FileNotFound);
		}

		let mut dir_block_buf = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(dir_block_addr, &mut dir_block_buf)
			.map_err(|_| FileError::BlockReadError)?;

		let entries = DirEntryBlock::new(&dir_block_buf);
		for (i, e) in entries.enumerate() {
			let used = (e.flags.get() & DIRENT_USED) != 0;
			if used {
				let nlen = e.name_len.get() as usize;
				if &e.name[..nlen] == filename.as_bytes() {
					// Found it!
					return Ok((i, e.inode.get(), dir_block_buf, dir_block_addr));
				}
			}
		}

		Err(FileError::FileNotFound)
	}

	/// generalised `create_directory_in_root`
	fn create_directory_in_dir(
		&mut self,
		parent_inode_num: u64, // The only new parameter
		name: &str,
	) -> Result<u64, FileSystemError> {
		if name.as_bytes().len() > DIR_NAME_MAX || name.is_empty() {
			return Err(FileSystemError::NameTooLong);
		}

		// Use the parent_inode_num instead of ROOT_DIRECTORY_INODE
		let root_dir_inode = self.read_inode(parent_inode_num)?;
		if root_dir_inode.mode != FileType::Directory {
			return Err(FileSystemError::CorruptLayout);
		}

		let dir_block_addr = root_dir_inode.direct_pointers[0];
		if dir_block_addr == 0 {
			return Err(FileSystemError::CorruptLayout);
		}

		let mut dir_block_buf = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(dir_block_addr, &mut dir_block_buf)
			.map_err(|_| FileSystemError::BlockError)?;

		// (Collision check is identical)
		let mut empty_slot_index: Option<usize> = None;
		let entries = DirEntryBlock::new(&dir_block_buf);
		for (i, entry) in entries.enumerate() {
			let is_used = (entry.flags.get() & DIRENT_USED) != 0;
			if is_used {
				let entry_name_len = entry.name_len.get() as usize;
				if &entry.name[..entry_name_len] == name.as_bytes() {
					println!("[FS] Directory with same name found");
					return Err(FileSystemError::AlreadyExists);
				}
			} else if empty_slot_index.is_none() {
				empty_slot_index = Some(i);
			}
		}
		let slot_index = empty_slot_index.ok_or(FileSystemError::NoSpace)?;

		// (Inode and data block allocation is identical)
		let new_inode_index = self.allocate_inode()?;
		let new_data_block = self.allocate_data_block()?;

		let mut new_inode = Inode {
			mode: FileType::Directory,
			user_id: 0,
			group_id: 0,
			link_count: 2,
			size_in_bytes: 0,
			last_access_time: 0,
			last_modification_time: 0,
			creation_time: 0,
			direct_pointers: [0u64; 10],
			indirect_pointer: 0,
		};

		new_inode.direct_pointers[0] = new_data_block;
		self.write_inode(new_inode, new_inode_index)?;

		let mut new_dir_block = [0u8; BLOCK_SIZE];

		// ".." points to its parent (the one that was passed in)
		self.write_dirent_into_block(&mut new_dir_block, 0, new_inode_index, b".")?;
		self.write_dirent_into_block(&mut new_dir_block, 1, parent_inode_num, b"..")?; // Use the parameter

		self.device
			.write_blocks(new_data_block, &new_dir_block)
			.map_err(|_| FileSystemError::BlockError)?;

		// (Writing the entry into the parent block is identical)
		self.write_dirent_into_block(
			&mut dir_block_buf,
			slot_index,
			new_inode_index,
			name.as_bytes(),
		)?;

		self.device
			.write_blocks(dir_block_addr, &dir_block_buf)
			.map_err(|_| FileSystemError::BlockError)?;

		println!("[FS] Created directory '{}' with inode #{}", name, new_inode_index);
		Ok(new_inode_index)
	}
}

/// Opaque handle representing an open file.
///
/// Contains the inode index of the file, allowing file operations to locate
/// and access the file's metadata and data blocks. Returned by `create_file`
/// and `open_file` operations.
///
/// # Note
/// The current implementation stores the raw inode index. In a more complete
/// filesystem, this would include additional state like:
/// - Current read/write position
/// - Access mode (read, write, append)
/// - Cached inode data
#[derive(Debug, Copy, Clone)]
pub struct FileHandler(pub usize);

/// Errors that can occur during high-level file operations.
///
/// These errors are returned by the `FileSystem` trait methods and provide
/// user-facing error information for file operations like create, delete, open.
#[derive(Debug)]
pub enum FileError {
	/// Failed to read a block from the device.
	BlockReadError,
	/// Directory has no free slots for new entries.
	DirectoryFull,
	/// Failed to write a block to the device.
	BlockWriteError,
	/// The requested file or directory was not found.
	FileNotFound,
	/// A file with the same name already exists.
	FileExists,
	/// File creation operation failed.
	CreationFailed,
	/// Filesystem has no space (inodes or data blocks exhausted).
	NoSpace,
	/// The provided FileHandler is invalid or doesn't correspond to a real file.
	InvalidHandle,
	/// Filename is invalid (empty, contains invalid characters, etc.).
	InvalidName,
	/// Filesystem structure is corrupted or inconsistent.
	Corrupt,
	/// Filename exceeds the maximum allowed length (DIR_NAME_MAX).
	NameTooLong,
}

/// Trait defining high-level filesystem operations.
///
/// This trait provides the primary interface for interacting with the filesystem.
/// Implementations handle file creation, deletion, opening, and directory listing.
pub trait FileSystem {
	/// Creates a new file at the specified path. The file is initially empty.
	///
	/// # Arguments
	/// * `name` - Path to the file (e.g., "/file.txt", "/dir/file.txt")
	///
	/// # Returns
	/// * `Ok(FileHandler)` - Handle to the newly created file
	/// * `Err(FileError)` - If creation fails (file exists, no space, etc.)
	fn create_file(
		&mut self,
		name: &str,
	) -> Result<FileHandler, FileError>;

	/// Removes a file from the filesystem, freeing its inode and data blocks.
	///
	/// # Arguments
	/// * `path` - Path to the file to delete
	///
	/// # Returns
	/// * `Ok(())` - If deletion was successful
	/// * `Err(FileError)` - If deletion fails (file not found, etc.)
	fn delete_file(
		&mut self,
		path: &str,
	) -> Result<(), FileError>;

	/// Opens an existing file and returns a handle for performing I/O operations.
	///
	/// # Arguments
	/// * `path` - Path to the file to open
	///
	/// # Returns
	/// * `Ok(FileHandler)` - Handle to the opened file
	/// * `Err(FileError)` - If file doesn't exist or cannot be opened
	fn open_file(
		&mut self,
		path: &str,
	) -> Result<FileHandler, FileError>;

	/// Lists all files and directories in the specified directory.
	///
	/// # Arguments
	/// * `path` - Path to the directory to list (e.g., "/", "/subdir")
	///
	/// # Returns
	/// * `Ok(Vec<String>)` - List of filenames in the directory
	/// * `Err(FileError)` - If directory doesn't exist or cannot be read
	fn list_file(
		&mut self,
		path: &str,
	) -> Result<Vec<String>, FileError>;

	/// Create a new directory
	///
	/// # Arguments
	/// * `path` - Path of the directory (e.g., "/", "/subdir")
	///
	/// # Returns
	/// * `Err(FileError)` - If directory doesn't exist or cannot be read
	fn create_directory(
		&mut self,
		path: &str,
	) -> Result<(), FileError>;
}

/// Low-level filesystem errors for internal operations.
///
/// These errors are used by internal filesystem methods that directly manipulate
/// blocks, bitmaps, inodes, and directory structures. They are more granular than
/// `FileError` and are often converted to `FileError` at higher layers.
#[derive(Debug)]
pub enum FileSystemError {
	/// An entry with the same name already exists.
	AlreadyExists,
	/// Block device I/O operation failed (read or write).
	BlockError,
	/// Filesystem structure is corrupted or inconsistent.
	CorruptLayout,
	/// Formatting operation failed (device too small, etc.).
	FormatFailed,
	/// Superblock validation failed (bad magic number, invalid layout).
	InvalidSuperBlock,
	/// Mount operation failed.
	MountFailed,
	/// Filename exceeds DIR_NAME_MAX bytes.
	NameTooLong,
	/// No free inodes or data blocks available.
	NoSpace,
}

impl<D: BlockDevice> FileSystem for SFS<D> {
	fn create_file(
		&mut self,
		path: &str,
	) -> Result<FileHandler, FileError> {
		// "/docs/new.txt" -> ("/docs", "new.txt")
		let (parent_path, basename) = Self::parse_path(path);
		if basename.is_empty() {
			return Err(FileError::InvalidName); // Can't create a file with no name
		}

		let parent_inode_num = self.find_inode_by_path(parent_path)?;

		let (new_inode_index, _dir_block) =
			self.create_file_in_dir(parent_inode_num, basename).map_err(|e| match e {
				FileSystemError::NameTooLong => FileError::InvalidName,
				FileSystemError::NoSpace => FileError::NoSpace,
				FileSystemError::CorruptLayout => FileError::Corrupt,
				FileSystemError::AlreadyExists => FileError::FileExists,
				_ => FileError::CreationFailed,
			})?;

		println!("[FS] Created file '{}' with inode #{}", path, new_inode_index);
		Ok(FileHandler(new_inode_index as usize))
	}

	fn delete_file(
		&mut self,
		path: &str,
	) -> Result<(), FileError> {
		let (parent_path, basename) = Self::parse_path(path);
		if basename.is_empty() || basename == "." || basename == ".." {
			return Err(FileError::InvalidName);
		}

		let parent_inode_num = self.find_inode_by_path(parent_path)?;

		let (slot, inode_idx, mut dir_block, dir_blk_addr) =
			self.find_entry_detailed(parent_inode_num, basename)?;

		if inode_idx == 0 {
			// should not happen
			return Err(FileError::FileNotFound);
		}

		let inode = self.read_inode(inode_idx).map_err(|_| FileError::Corrupt)?;
		// TODO: add check here so that we don't delete a non-empty directory - not necessary now!
		if inode.mode == FileType::Directory {
			return Err(FileError::InvalidName); // is a directory
		}

		for &dp in &inode.direct_pointers {
			if dp != 0 {
				self.free_data_block(dp).map_err(|_| FileError::Corrupt)?;
			}
		}

		// free the inode
		self.free_inode(inode_idx).map_err(|_| FileError::Corrupt)?;

		// clearing the directory entries here
		let start = slot * DIR_ENTRY_SIZE;
		for b in &mut dir_block[start..start + DIR_ENTRY_SIZE] {
			*b = 0;
		}

		self.device
			.write_blocks(dir_blk_addr, &dir_block)
			.map_err(|_| FileError::BlockWriteError)?;

		println!("[FS] Deleted file '{}' (inode #{})", path, inode_idx);
		Ok(())
	}

	fn open_file(
		&mut self,
		path: &str,
	) -> Result<FileHandler, FileError> {
		let inode_idx = self.find_inode_by_path(path)?;
		Ok(FileHandler(inode_idx as usize))
	}

	fn list_file(
		&mut self,
		path: &str, // The trait now passes us a path
	) -> Result<Vec<String>, FileError> {
		let dir_inode_num = self.find_inode_by_path(path)?;
		let dir_inode = self.read_inode(dir_inode_num).map_err(|_| FileError::Corrupt)?;

		if dir_inode.mode != FileType::Directory {
			// You can't 'ls' a file!
			return Err(FileError::InvalidName);
		}

		let block = dir_inode.direct_pointers[0];
		if block == 0 {
			return Ok(Vec::new()); // Empty directory
		}

		let mut buf = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(block, &mut buf)
			.map_err(|_| FileError::BlockReadError)?;

		let mut res = Vec::new();
		let entries = DirEntryBlock::new(&buf);
		for e in entries {
			let used = (e.flags.get() & DIRENT_USED) != 0;
			if used && e.inode.get() != 0 {
				let nlen = e.name_len.get() as usize;
				if nlen >= DIR_NAME_MAX {
					return Err(FileError::NameTooLong);
				}
				let name_slice = &e.name[..nlen];
				if let Ok(s) = core::str::from_utf8(name_slice) {
					res.push(s.to_string());
				}
			}
		}

		Ok(res)
	}

	fn create_directory(
		&mut self,
		path: &str,
	) -> Result<(), FileError> {
		let (parent_path, basename) = Self::parse_path(path);
		if basename.is_empty() {
			return Err(FileError::InvalidName);
		}
		// we need to find the inode of the parent directory
		let parent_inode_num = self.find_inode_by_path(parent_path)?;
		// create the directory in that parent
		self.create_directory_in_dir(parent_inode_num, basename).map_err(|e| match e {
			FileSystemError::NameTooLong => FileError::InvalidName,
			FileSystemError::NoSpace => FileError::NoSpace,
			FileSystemError::CorruptLayout => FileError::Corrupt,
			FileSystemError::AlreadyExists => FileError::FileExists,
			_ => FileError::CreationFailed,
		})?;

		Ok(())
	}
}

impl<D: BlockDevice> SFS<D> {
	/// Writes multiple lines of text to a file.
	///
	/// Joins the provided lines with newline characters and writes them to the file's
	/// first data block. This is a simplified write operation that overwrites any
	/// existing content and only supports files up to one block (512 bytes).
	///
	/// # Arguments
	/// * `handle` - FileHandler obtained from create_file or open_file
	/// * `lines` - Array of string slices, each representing a line to write
	///
	/// # Returns
	/// * `Ok(())` - If write was successful
	/// * `Err(FileError::Corrupt)` - If handle is invalid or points to a non-file
	/// * `Err(FileError::NoSpace)` - If content exceeds BLOCK_SIZE or no blocks available
	/// * `Err(FileError::BlockWriteError)` - If block write fails
	///
	/// # Implementation Details
	/// - Joins lines with "\n" separator
	/// - Allocates first data block if not already allocated
	/// - Writes to only the first direct pointer (single-block files only)
	/// - Updates inode size metadata
	/// - Persists inode changes to disk
	///
	/// # Limitations
	/// - Maximum file size: 512 bytes (BLOCK_SIZE)
	/// - Overwrites existing content (not append)
	/// - Does not update timestamps
	/// - Does not support multi-block files or indirect pointers
	pub fn write_file_lines(
		&mut self,
		handle: FileHandler,
		lines: &[&str], // reference to a string slice? -- string slice is reference right?
	) -> Result<(), FileError> {
		let inode_idx = handle.0 as u64;
		let mut inode = self.read_inode(inode_idx).map_err(|_| FileError::Corrupt)?;
		if inode.mode != FileType::File {
			return Err(FileError::Corrupt);
		}

		// append a new line to whatever the user just added
		let joined = lines.join("\n");
		let bytes = joined.as_bytes();

		if bytes.len() > BLOCK_SIZE {
			return Err(FileError::NoSpace);
			// simple check -- maybe add some proper warning here
			// to the user when he tries to save
		}

		// check for data block allocation
		if inode.direct_pointers[0] == 0 {
			let b = self.allocate_data_block().map_err(|_| FileError::NoSpace)?;
			inode.direct_pointers[0] = b;
		}

		let data_block = inode.direct_pointers[0];

		let mut buf = [0u8; BLOCK_SIZE];
		buf[..bytes.len()].copy_from_slice(bytes);

		// wrote into the buffer
		// now have to write this into disk
		self.device
			.write_blocks(data_block, &buf)
			.map_err(|_| FileError::BlockWriteError)?;

		// we also need to update inode metadata
		inode.size_in_bytes = bytes.len() as u64;
		// timestamps for inode are missing
		// not a priority but nice to have
		self.write_inode(inode, inode_idx).map_err(|_| FileError::BlockWriteError)?;
		Ok(())
	}

	/// Reads the entire content of a file as a UTF-8 string.
	///
	/// Reads the file's data from its first data block and returns it as a String.
	/// This is a simplified read operation that only supports single-block files.
	///
	/// # Arguments
	/// * `handle` - FileHandler obtained from create_file or open_file
	///
	/// # Returns
	/// * `Ok(String)` - The file contents as a UTF-8 string
	/// * `Err(FileError::Corrupt)` - If:
	///   - Handle is invalid or points to a non-file
	///   - File has size but no data block
	///   - Content is not valid UTF-8
	/// * `Err(FileError::BlockReadError)` - If block read fails
	///
	/// # Implementation Details
	/// - Returns empty string for zero-size files
	/// - Reads from only the first direct pointer
	/// - Uses inode.size_in_bytes to determine valid data length
	/// - Validates UTF-8 encoding
	/// - Allocates a String to return the content
	///
	/// # Limitations
	/// - Only reads files up to one block (512 bytes)
	/// - Requires content to be valid UTF-8
	/// - Does not support multi-block files or indirect pointers
	pub fn read_file(
		&mut self,
		handle: FileHandler,
	) -> Result<String, FileError> {
		let inode_idx = handle.0 as u64;
		let inode = self.read_inode(inode_idx).map_err(|_| FileError::Corrupt)?;
		if inode.mode != FileType::File {
			return Err(FileError::Corrupt);
		}

		let sz = inode.size_in_bytes as usize;
		if sz == 0 {
			return Ok(String::new());
		}

		let data_block = inode.direct_pointers[0];
		if data_block == 0 {
			return Err(FileError::Corrupt);
		}

		let mut buf = [0u8; BLOCK_SIZE];
		self.device
			.read_blocks(data_block, &mut buf)
			.map_err(|_| FileError::BlockReadError)?;

		let slice = &buf[..sz];
		let s = core::str::from_utf8(slice).map_err(|_| FileError::Corrupt)?;
		// should I make different types of corrupt?
		// maybe some good verbose output for user would be better -- look for crates for this!
		Ok(s.to_string())
	}
}

/// Type alias for the concrete filesystem type used in this OS.
///
/// Defines the global filesystem as an SFS backed by a VirtIO block device
/// with PCI transport. This type is used for static filesystem instances
/// and ensures type consistency across the kernel.
///
/// # Components
/// - `SFS<D>`: The Simple File System implementation
/// - `VirtIOBlk<OsHal, PciTransport>`: VirtIO block device driver
///   - `OsHal`: OS-specific hardware abstraction layer
///   - `PciTransport`: PCI bus transport for VirtIO
///
/// # Usage
/// This type can be stored in static variables or used for type annotations
/// where the specific filesystem configuration needs to be explicit.
// Exact type of the file system that we're going to use
// the memory mapped regions of the VirtIOBlk device live forever?
pub type GLOBALFSType = SFS<VirtIOBlk<OsHal, PciTransport>>; // this does not expect a lifetime
