# .cargo/config.toml

[build]
target = "x86_64-blog_os.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
panic_abort_tests = true

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
