name: Rust Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: sudo apt update && sudo apt install -y rustc cargo
    - name: Build
      run: cargo build --verbose
