name: Running Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-x86_64-unknown-linux-gnu
          override: true
          components: rust-src, llvm-tools-preview

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y qemu-system-x86  # installs QEMU for x86 targets

      - name: Install Rust and Bootimage
        run: |
          # Update rustup and install the nightly toolchain
          rustup self update
          rustup update nightly
          # Add the rust-src component for the target
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          # Install bootimage using cargo
          cargo install bootimage
          # Ensure cargo bin folder is in PATH
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Run Tests
        run: cargo test --target x86_64-blog_os.json --verbose
