name: Running Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: |
        sudo apt update && sudo apt install -y rustc cargo
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Run Tests
      run: cargo test --verbose
